### ISSUE TITLE
Issue in compact mode

### ISSUE THREAD

**Issue by shahmilav** [zvuc/firefox-sliding-bookmarks-bar#3]
Hey, first of all thanks so much for the great CSS.

In Firefox (currently running Dev edition 97.0b9), I have enabled compact mode. However, the tops of the icons in the bookmarks bar get cut off. Any way to fix this?

<img width="1295" alt="Screen Shot 2022-02-06 at 11 26 07 AM" src="https://user-images.githubusercontent.com/53659750/152690721-ee32d4e9-377f-411e-89c0-e29a53d6b82a.png">

As you can see in the image, the icons get cut.

**Comment by shahmilav** [comment]
Well, what do you know, solved this right after posting the issue. Changing 
`:root {
--toolbar-offset-height:⋅37px;
}
` from 42px did the trick.

**Comment by zvuc** [comment]
👍👍
I didn't know compact tabbar was making a comeback :D 
I'll try including an automatic detection for compact mode to adjust for the changed heights, when 97 comes to stable.

**Comment by shahmilav** [comment]
Yeah, it is still an `about:config` setting, yet more people are starting to use it.
