### ISSUE TITLE
README is missing documentation about `:has()` selector.

### ISSUE THREAD

**Issue by eramdam** [zvuc/firefox-sliding-bookmarks-bar#5]
I was trying to use this bit of CSS and noticed it wasn't working, after troubleshooting I found that it was because of the use of the `:has()` CSS selector, which isn't enabled by default on Firefox yet. The README should probably needs to be updated to mention that users need to enable `layout.css.has-selector.enabled` before this style works properly 😄

**Comment by zvuc** [comment]
Whoopsies, sorry about that! 
I was experimenting some stuff with the yet unreleased `:has()` selector, and used it to target a specific state where bookmark dropdown menu was open (technically you aren't hovering on the menu with your mouse, so the menu would retract). While it worked, I meant it as an additional added benefit for browsers with the option on (and for future Firefox versions where the flag would be enabled by default), seems like Firefox had trouble parsing the declaration block entirely when it had unsupported selector syntax within 😅 

I pushed a fix, it should now work regardless of `:has()` support!
Thanks for letting me know :D
