### ISSUE TITLE
sliding bookmarks not compatible with Translucent Tabbar

### ISSUE THREAD

**Issue by Quickshadoww** [zvuc/firefox-sliding-bookmarks-bar#6]
sadly when i put both css codes into my userchrome the translucent tabbar effect gets wiped away. any way to fix it maybe ? =) thanks for your work tho

**Comment by zvuc** [comment]
Whoops turns out I forgot to check the latest release as latest (Old version 108 was showing up as the latest release in sidebar). Get the 127 version and you should get compatibility with the translucency.

Cheers :D
